include ../share/make_common.mk

LIBNAME:=bsp
SOURCES:=$(wildcard libsrc/*.[cS])
CFLAGS += -I${WORKSPACE}/bsp_tile0_mb/tile0_mb/include/ -I$(WORKSPACE)/tiles -Iinclude/

include ../share/make_library.mk
