include ../share/make_common.mk

LIBNAME:=userchannel-riscv
SOURCES:=$(wildcard libsrc/*.[cS])
CFLAGS += -I${WORKSPACE}/libbsp/include/ -I$(WORKSPACE)/tiles -Iinclude/


include ../share/make_library.mk
