include ../../vep_0/share/make_common.mk

LIBNAME:= canmac
SOURCES:=$(wildcard libsrc/*.[cS])
CFLAGS += -I${SYSVEP}/libbsp/include/ -I$(SYSVEP)/tiles -Iinclude/ -I../shared

include ../../vep_0/share/make_library.mk
